"""add table combination rules

Revision ID: 0b9fc2d912b6
Revises: 8c2378621a3d
Create Date: 2026-09-17 06:05:51.510528
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9fc2d912b6'
down_revision: Union[str, None] = '8c2378621a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_combination_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('service_area_id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('member_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('auto', 'confirmed', 'blocked', name='table_combination_rule_status'), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_area_id'], ['service_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_plan_id', 'member_key', name='uq_table_combination_rules_floor_member_key')
    )
    op.create_index(op.f('ix_table_combination_rules_floor_plan_id'), 'table_combination_rules', ['floor_plan_id'], unique=False)
    op.create_index(op.f('ix_table_combination_rules_restaurant_id'), 'table_combination_rules', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_table_combination_rules_service_area_id'), 'table_combination_rules', ['service_area_id'], unique=False)
    op.create_index(op.f('ix_table_combination_rules_status'), 'table_combination_rules', ['status'], unique=False)
    op.create_table('table_combination_rule_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['table_combination_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'table_id', name='uq_table_combination_rule_members_rule_table')
    )
    op.create_index(op.f('ix_table_combination_rule_members_rule_id'), 'table_combination_rule_members', ['rule_id'], unique=False)
    op.create_index(op.f('ix_table_combination_rule_members_table_id'), 'table_combination_rule_members', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_combination_rule_members_table_id'), table_name='table_combination_rule_members')
    op.drop_index(op.f('ix_table_combination_rule_members_rule_id'), table_name='table_combination_rule_members')
    op.drop_table('table_combination_rule_members')
    op.drop_index(op.f('ix_table_combination_rules_status'), table_name='table_combination_rules')
    op.drop_index(op.f('ix_table_combination_rules_service_area_id'), table_name='table_combination_rules')
    op.drop_index(op.f('ix_table_combination_rules_restaurant_id'), table_name='table_combination_rules')
    op.drop_index(op.f('ix_table_combination_rules_floor_plan_id'), table_name='table_combination_rules')
    op.drop_table('table_combination_rules')
    sa.Enum(
        'auto',
        'confirmed',
        'blocked',
        name='table_combination_rule_status',
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
