"""add restaurant learning profiles

Revision ID: 1a4d3b38e802
Revises: b51bac42f191
Create Date: 2026-08-06 09:09:49.054135
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4d3b38e802'
down_revision: Union[str, None] = 'b51bac42f191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_learning_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('suggestions_created', sa.Integer(), nullable=False),
    sa.Column('suggestions_read', sa.Integer(), nullable=False),
    sa.Column('suggestions_accepted', sa.Integer(), nullable=False),
    sa.Column('suggestions_dismissed', sa.Integer(), nullable=False),
    sa.Column('suggestions_expired', sa.Integer(), nullable=False),
    sa.Column('accepted_score_average', sa.Float(), nullable=True),
    sa.Column('dismissed_score_average', sa.Float(), nullable=True),
    sa.Column('accepted_moves_average', sa.Float(), nullable=True),
    sa.Column('accepted_seat_waste_average', sa.Float(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('dismissal_rate', sa.Float(), nullable=False),
    sa.Column('read_rate', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('last_processed_event_id', sa.UUID(), nullable=True),
    sa.Column('last_processed_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_processed_event_id'], ['intelligence_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', name='uq_restaurant_learning_profiles_restaurant_id')
    )
    op.create_index('ix_restaurant_learning_profiles_last_processed_event_at', 'restaurant_learning_profiles', ['last_processed_event_at'], unique=False)
    op.create_index(op.f('ix_restaurant_learning_profiles_last_processed_event_id'), 'restaurant_learning_profiles', ['last_processed_event_id'], unique=False)
    op.create_index(op.f('ix_restaurant_learning_profiles_restaurant_id'), 'restaurant_learning_profiles', ['restaurant_id'], unique=False)
    op.create_index('ix_restaurant_learning_profiles_updated_at', 'restaurant_learning_profiles', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurant_learning_profiles_updated_at', table_name='restaurant_learning_profiles')
    op.drop_index(op.f('ix_restaurant_learning_profiles_restaurant_id'), table_name='restaurant_learning_profiles')
    op.drop_index(op.f('ix_restaurant_learning_profiles_last_processed_event_id'), table_name='restaurant_learning_profiles')
    op.drop_index('ix_restaurant_learning_profiles_last_processed_event_at', table_name='restaurant_learning_profiles')
    op.drop_table('restaurant_learning_profiles')
    # ### end Alembic commands ###
