"""add move complexity learning averages

Revision ID: 21338362ec8f
Revises: 8c7e2d91f4a6
Create Date: 2026-08-24 11:13:44.326052
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21338362ec8f'
down_revision: Union[str, None] = '8c7e2d91f4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_learning_profiles', sa.Column('accepted_move_complexity_average', sa.Float(), nullable=True))
    op.add_column('restaurant_learning_profiles', sa.Column('dismissed_move_complexity_average', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_learning_profiles', 'dismissed_move_complexity_average')
    op.drop_column('restaurant_learning_profiles', 'accepted_move_complexity_average')
    # ### end Alembic commands ###
