"""add table combinations

Revision ID: 56e14548ca0a
Revises: ccf8fcc5d9ae
Create Date: 2026-08-01 10:37:38.482673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e14548ca0a'
down_revision: Union[str, None] = 'ccf8fcc5d9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_combinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('service_area_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_capacity', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('setup_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_area_id'], ['service_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_table_combinations_restaurant_name')
    )
    op.create_index(op.f('ix_table_combinations_restaurant_id'), 'table_combinations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_table_combinations_service_area_id'), 'table_combinations', ['service_area_id'], unique=False)
    op.create_table('table_combination_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('combination_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['combination_id'], ['table_combinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combination_id', 'table_id', name='uq_table_combination_members_combination_table')
    )
    op.create_index(op.f('ix_table_combination_members_combination_id'), 'table_combination_members', ['combination_id'], unique=False)
    op.create_index(op.f('ix_table_combination_members_table_id'), 'table_combination_members', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_combination_members_table_id'), table_name='table_combination_members')
    op.drop_index(op.f('ix_table_combination_members_combination_id'), table_name='table_combination_members')
    op.drop_table('table_combination_members')
    op.drop_index(op.f('ix_table_combinations_service_area_id'), table_name='table_combinations')
    op.drop_index(op.f('ix_table_combinations_restaurant_id'), table_name='table_combinations')
    op.drop_table('table_combinations')
    # ### end Alembic commands ###
