"""add billing fields to users

Revision ID: 70f3fb67ffd9
Revises: f465a1572227
Create Date: 2026-06-09 10:41:51.621302
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f3fb67ffd9'
down_revision: Union[str, None] = 'f465a1572227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        'users',
        sa.Column(
            'subscription_status',
            sa.String(length=50),
            nullable=False,
            server_default='inactive',
        ),
    )

    op.add_column(
        'users',
        sa.Column(
            'stripe_customer_id',
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.add_column(
        'users',
        sa.Column(
            'stripe_subscription_id',
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.add_column(
        'users',
        sa.Column(
            'trial_start_date',
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        'users',
        sa.Column(
            'trial_end_date',
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        'users',
        sa.Column(
            'subscription_start_date',
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        'users',
        sa.Column(
            'subscription_end_date',
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        'users',
        sa.Column(
            'has_used_trial',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_used_trial')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_start_date')
    op.drop_column('users', 'trial_end_date')
    op.drop_column('users', 'trial_start_date')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
