"""add ai suggestions

Revision ID: 776d343c63ba
Revises: bdc0c67f35ec
Create Date: 2026-08-05 04:50:09.746014
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '776d343c63ba'
down_revision: Union[str, None] = 'bdc0c67f35ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('suggestion_type', sa.Enum('reoptimization', 'capacity', 'table_release', name='ai_suggestion_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', 'expired', name='ai_suggestion_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_reservation_id'), 'ai_suggestions', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_restaurant_id'), 'ai_suggestions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_status'), 'ai_suggestions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_ai_suggestions_status"),
        table_name="ai_suggestions",
    )
    op.drop_index(
        op.f("ix_ai_suggestions_restaurant_id"),
        table_name="ai_suggestions",
    )
    op.drop_index(
        op.f("ix_ai_suggestions_reservation_id"),
        table_name="ai_suggestions",
    )

    op.drop_table("ai_suggestions")

    sa.Enum(
        name="ai_suggestion_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(
        name="ai_suggestion_type",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
