"""add table floor plan fields

Revision ID: 806250fce884
Revises: ee13b17477db
Create Date: 2026-07-20 08:11:49.156584
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806250fce884'
down_revision: Union[str, None] = 'ee13b17477db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tables', 
        sa.Column(
            'x', 
            sa.Integer(), 
            nullable=False,
            server_default="0",
            ),
    )
    op.add_column(
        'tables', 
        sa.Column(
            'y', 
            sa.Integer(), 
            nullable=False,
            server_default="0",
            ),
    )
    op.add_column(
        'tables', 
        sa.Column(
            'width', 
            sa.Integer(), 
            nullable=False,
            server_default="80",
            ),
    )
    op.add_column(
        'tables', 
        sa.Column(
            'height', 
            sa.Integer(), 
            nullable=False,
            server_default="80",
            ),
    )
    op.add_column(
        'tables', 
        sa.Column(
            'shape', 
            sa.String(length=20), 
            nullable=False,
            server_default="square",
            ),
    )
    op.add_column(
        'tables', 
        sa.Column(
            'rotation', 
            sa.Integer(), 
            nullable=False,
            server_default="0",
            ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'rotation')
    op.drop_column('tables', 'shape')
    op.drop_column('tables', 'height')
    op.drop_column('tables', 'width')
    op.drop_column('tables', 'y')
    op.drop_column('tables', 'x')
    # ### end Alembic commands ###
