"""add smart layout combination key

Revision ID: 9831eded325d
Revises: 0a36da107eee
Create Date: 2026-09-19 06:06:03.669381
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9831eded325d'
down_revision: Union[str, None] = '0a36da107eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_combinations', sa.Column('smart_layout_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_combinations', 'smart_layout_key')
    # ### end Alembic commands ###
