"""add table id to reservations

Revision ID: 9fe8b3b43c25
Revises: a869d9f5c789
Create Date: 2026-05-30 14:07:19.450387
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe8b3b43c25'
down_revision: Union[str, None] = 'a869d9f5c789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('table_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reservations_table_id'), 'reservations', ['table_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'tables', ['table_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_table_id'), table_name='reservations')
    op.drop_column('reservations', 'table_id')
    # ### end Alembic commands ###
