"""connect reservations to restaurants

Revision ID: a5afdefea4c3
Revises: d5a84beb54e3
Create Date: 2026-05-11 16:14:38.679888
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5afdefea4c3'
down_revision: Union[str, None] = 'd5a84beb54e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
