"""link smart layout rules to table combinations

Revision ID: a640d1ef7065
Revises: 0b9fc2d912b6
Create Date: 2026-09-17 07:11:34.110004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a640d1ef7065'
down_revision: Union[str, None] = '0b9fc2d912b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_combinations', sa.Column('smart_layout_rule_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_table_combinations_smart_layout_rule_id'), 'table_combinations', ['smart_layout_rule_id'], unique=True)
    op.create_foreign_key(None, 'table_combinations', 'table_combination_rules', ['smart_layout_rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_combinations', type_='foreignkey')
    op.drop_index(op.f('ix_table_combinations_smart_layout_rule_id'), table_name='table_combinations')
    op.drop_column('table_combinations', 'smart_layout_rule_id')
    # ### end Alembic commands ###
