"""add intelligence event store

Revision ID: b51bac42f191
Revises: 776d343c63ba
Create Date: 2026-08-06 01:45:18.515758
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b51bac42f191'
down_revision: Union[str, None] = '776d343c63ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('reservation_created', 'reservation_updated', 'reservation_cancelled', 'reservation_moved', 'ai_suggestion_created', 'ai_suggestion_read', 'ai_suggestion_accepted', 'ai_suggestion_dismissed', 'ai_suggestion_expired', 'seating_plan_applied', 'table_assignment_created', 'conversation_started', 'conversation_completed', 'guest_no_show', 'guest_completed_visit', 'manual_override', name='intelligence_event_type'), nullable=False),
    sa.Column('source', sa.Enum('system', 'manager', 'guest', 'ai', 'integration', name='intelligence_event_source'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_event_id', sa.UUID(), nullable=True),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['causation_event_id'], ['intelligence_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_events_actor_user_id'), 'intelligence_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_causation_event_id'), 'intelligence_events', ['causation_event_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_correlation_id'), 'intelligence_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_created_at'), 'intelligence_events', ['created_at'], unique=False)
    op.create_index('ix_intelligence_events_entity', 'intelligence_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_entity_id'), 'intelligence_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_entity_type'), 'intelligence_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_intelligence_events_event_type'), 'intelligence_events', ['event_type'], unique=False)
    op.create_index('ix_intelligence_events_event_type_created', 'intelligence_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_intelligence_events_occurred_at'), 'intelligence_events', ['occurred_at'], unique=False)
    op.create_index('ix_intelligence_events_restaurant_created', 'intelligence_events', ['restaurant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_intelligence_events_restaurant_id'), 'intelligence_events', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_source'), 'intelligence_events', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f(
            "ix_intelligence_events_source",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_restaurant_id",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        "ix_intelligence_events_restaurant_created",
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_occurred_at",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        "ix_intelligence_events_event_type_created",
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_event_type",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_entity_type",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_entity_id",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        "ix_intelligence_events_entity",
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_created_at",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_correlation_id",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_causation_event_id",
        ),
        table_name="intelligence_events",
    )
    op.drop_index(
        op.f(
            "ix_intelligence_events_actor_user_id",
        ),
        table_name="intelligence_events",
    )

    op.drop_table("intelligence_events")

    sa.Enum(
        name="intelligence_event_source",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(
        name="intelligence_event_type",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
