"""add reservation table assignments

Revision ID: ccf8fcc5d9ae
Revises: d0bf9dfa91e7
Create Date: 2026-07-31 13:06:40.714507
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = 'ccf8fcc5d9ae'
down_revision: Union[str, None] = 'd0bf9dfa91e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_table_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'table_id', name='uq_reservation_table_assignment')
    )
    op.create_index(op.f('ix_reservation_table_assignments_reservation_id'), 'reservation_table_assignments', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_table_assignments_table_id'), 'reservation_table_assignments', ['table_id'], unique=False)
    connection = op.get_bind()

    existing_reservations = connection.execute(
        sa.text("""
            SELECT id, table_id
            FROM reservations
            WHERE table_id IS NOT NULL
        """)
    ).mappings().all()

    if existing_reservations:
        assignments_table = sa.table(
            "reservation_table_assignments",
            sa.column("id", sa.UUID()),
            sa.column("reservation_id", sa.UUID()),
            sa.column("table_id", sa.UUID()),
            sa.column("is_primary", sa.Boolean()),
        )

        op.bulk_insert(
            assignments_table,
            [
                {
                    "id": uuid.uuid4(),
                    "reservation_id": reservation["id"],
                    "table_id": reservation["table_id"],
                    "is_primary": True,
                }
                for reservation in existing_reservations
            ],
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_table_assignments_table_id'), table_name='reservation_table_assignments')
    op.drop_index(op.f('ix_reservation_table_assignments_reservation_id'), table_name='reservation_table_assignments')
    op.drop_table('reservation_table_assignments')
    # ### end Alembic commands ###
