"""create restaurants and relations

Revision ID: d5a84beb54e3
Revises: 0001_initial
Create Date: 2026-05-11 14:45:28.666280
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a84beb54e3'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('opening_hour', sa.Integer(), nullable=False),
    sa.Column('closing_hour', sa.Integer(), nullable=False),
    sa.Column('number_of_tables', sa.Integer(), nullable=False),
    sa.Column('concierge_tone', sa.String(length=100), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.drop_constraint('conversations_session_id_key', 'conversations', type_='unique')
    op.add_column('reservations', sa.Column('restaurant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reservations_restaurant_id'), 'reservations', ['restaurant_id'], unique=False)
    op.create_index('ix_reservations_restaurant_time', 'reservations', ['restaurant_id', 'reservation_time'], unique=False)
    op.create_foreign_key(None, 'reservations', 'restaurants', ['restaurant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index('ix_reservations_restaurant_time', table_name='reservations')
    op.drop_index(op.f('ix_reservations_restaurant_id'), table_name='reservations')
    op.drop_column('reservations', 'restaurant_id')
    op.create_unique_constraint('conversations_session_id_key', 'conversations', ['session_id'])
    op.drop_table('restaurants')
    # ### end Alembic commands ###
