"""add owner id to restaurants

Revision ID: d98f4016b3ca
Revises: 06b0ad744c6b
Create Date: 2026-05-12 17:33:42.088336
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98f4016b3ca'
down_revision: Union[str, None] = '06b0ad744c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
