"""add integration models

Revision ID: ee13b17477db
Revises: 70f3fb67ffd9
Create Date: 2026-06-21 14:40:09.092381
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
provider_type_enum = sa.Enum(
    'alias_native',
    'sevenrooms',
    'opentable',
    'resdiary',
    'thefork',
    name='integration_provider_type',
)

integration_mode_enum = sa.Enum(
    'standalone',
    'connect',
    name='integration_mode',
)

integration_status_enum = sa.Enum(
    'active',
    'pending',
    'disabled',
    'error',
    name='integration_status',
)

operation_type_enum = sa.Enum(
    'create_reservation',
    'update_reservation',
    'cancel_reservation',
    name='integration_operation_type',
)

operation_status_enum = sa.Enum(
    'pending',
    'succeeded',
    'failed',
    'in_doubt',
    name='integration_operation_status',
)

# revision identifiers, used by Alembic.
revision: str = 'ee13b17477db'
down_revision: Union[str, None] = '70f3fb67ffd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', provider_type_enum, nullable=False),
    sa.Column('operation_type', operation_type_enum, nullable=False),
    sa.Column('status', operation_status_enum, nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_operations_idempotency_key'), 'integration_operations', ['idempotency_key'], unique=True)
    op.create_index('ix_integration_operations_provider_status', 'integration_operations', ['provider_type', 'status'], unique=False)
    op.create_index(op.f('ix_integration_operations_restaurant_id'), 'integration_operations', ['restaurant_id'], unique=False)
    op.create_index('ix_integration_operations_restaurant_status', 'integration_operations', ['restaurant_id', 'status'], unique=False)
    op.create_table('restaurant_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', provider_type_enum, nullable=False),
    sa.Column('mode', integration_mode_enum, nullable=False),
    sa.Column('status', integration_status_enum, nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('encrypted_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_integrations_restaurant_id'), 'restaurant_integrations', ['restaurant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_integrations_restaurant_id'), table_name='restaurant_integrations')
    op.drop_table('restaurant_integrations')
    op.drop_index('ix_integration_operations_restaurant_status', table_name='integration_operations')
    op.drop_index(op.f('ix_integration_operations_restaurant_id'), table_name='integration_operations')
    op.drop_index('ix_integration_operations_provider_status', table_name='integration_operations')
    op.drop_index(op.f('ix_integration_operations_idempotency_key'), table_name='integration_operations')
    op.drop_table('integration_operations')
    # ### end Alembic commands ###
