"""
Re-export all ORM models.

Importing them here ensures SQLAlchemy registers them on `Base.metadata`,
which Alembic needs for autogenerated migrations.
"""
from app.models.conversation import Conversation, Message, MessageRole
from app.models.reservation import Reservation, ReservationStatus
from app.models.restaurant import Restaurant
from app.models.table import Table
from app.models.user import User
from app.models.integration import (
    IntegrationMode,
    IntegrationOperation,
    IntegrationStatus,
    OperationStatus,
    OperationType,
    ProviderType,
    RestaurantIntegration,
)

__all__ = [
    "Conversation",
    "Message",
    "MessageRole",
    "Reservation",
    "ReservationStatus",
    "User",
    "Restaurant",
    "Table",
    "IntegrationMode",
    "IntegrationOperation",
    "IntegrationStatus",
    "OperationStatus",
    "OperationType",
    "ProviderType",
    "RestaurantIntegration",
    
]