"""
Re-export all ORM models.

Importing them here ensures SQLAlchemy registers them on `Base.metadata`,
which Alembic needs for autogenerated migrations.
"""
from app.models.conversation import Conversation, Message, MessageRole
from app.models.reservation import Reservation, ReservationStatus
from app.models.restaurant import Restaurant
from app.models.service_area import ServiceArea
from app.models.floor_plan import FloorPlan
from app.models.table_placement import TablePlacement
from app.models.table import Table
from app.models.reservation_table_assignment import ReservationTableAssignment
from app.models.table_combination import (
    TableCombination,
    TableCombinationMember,
)
from app.models.user import User
from app.models.integration import (
    IntegrationMode,
    IntegrationOperation,
    IntegrationStatus,
    OperationStatus,
    OperationType,
    ProviderType,
    RestaurantIntegration,
)

from app.models.ai_suggestion import (
    AISuggestion,
    AISuggestionStatus,
    AISuggestionType,
)

__all__ = [
    "Conversation",
    "Message",
    "MessageRole",
    "Reservation",
    "ReservationStatus",
    "TableCombination",
    "TableCombinationMember",
    "AISuggestion",
    "AISuggestionStatus",
    "AISuggestionType",
    "User",
    "Restaurant",
    "ServiceArea",
    "FloorPlan",
    "Table",
    "ReservationTableAssignment",
    "TablePlacement",
    "IntegrationMode",
    "IntegrationOperation",
    "IntegrationStatus",
    "OperationStatus",
    "OperationType",
    "ProviderType",
    "RestaurantIntegration",
    
]