"""
Re-export all ORM models.

Importing them here ensures SQLAlchemy registers them on `Base.metadata`,
which Alembic needs for autogenerated migrations.
"""
from app.models.conversation import Conversation, Message, MessageRole
from app.models.reservation import Reservation, ReservationStatus
from app.models.restaurant import Restaurant
from app.models.user import User

__all__ = [
    "Conversation",
    "Message",
    "MessageRole",
    "Reservation",
    "ReservationStatus",
    "User",
    "Restaurant",
    
]